
name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."

      - name: Deploy
        run:  ssh webadmin@server 'bash -s' < /scripts/deploy_frontend.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
